---
exclude_paths:
  - spec/fixtures
  - bin/puppet

detectors:
  TooManyStatements:
    enabled: false

  NestedIterators:
    enabled: false

  LongParameterList:
    enabled: false

  UncommunicativeVariableName:
    enabled: false

  DuplicateMethodCall:
    enabled: false

  NilCheck:
    enabled: false
