---
require: rubocop-performance

AllCops:
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'bin/*.rb'
    - 'spec/**/*.rb'
    - 'spec/**/Puppetfile'
    - puppet-check.gemspec
    - Gemfile
    - Rakefile
    - Vagrantfile
  Exclude:
    - 'spec/fixtures/**/*'
    - 'bin/puppet'

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

# false triggers for this cop
Style/EvalWithLocation:
  Enabled: false

# probably can remove after rails cops removed from core
Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
