---
require: rubocop-performance

AllCops:
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'bin/*.rb'
    - 'spec/**/*.rb'
    - 'spec/**/Puppetfile'
    - puppet-check.gemspec
    - Gemfile
    - Rakefile
    - Vagrantfile
  Exclude:
    - 'spec/fixtures/**/*'
    - 'bin/puppet'

# twenty-first century
Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

# why
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# poor coding practices
Naming/RescuedExceptionsVariableName:
  Enabled: false

# false triggers
Style/EvalWithLocation:
  Enabled: false

# false positives
Style/FrozenStringLiteralComment:
  Enabled: false

# why
Style/ClassAndModuleChildren:
  Enabled: false

# poor practices
Gemspec/DevelopmentDependencies:
  Enabled: false

# encourages unreadable code
Style/IfUnlessModifier:
  Enabled: false
