---
require: rubocop-performance

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'bin/*.rb'
    - 'spec/**/*.rb'
    - 'spec/**/Puppetfile'
    - puppet-check.gemspec
    - Gemfile
    - Rakefile
    - Vagrantfile
  Exclude:
    - 'spec/fixtures/**/*'
    - 'bin/puppet'

Metrics:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
