---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    parameters:
      ruby-version:
        type: string
    docker:
    - image: ruby:<< parameters.ruby-version >>-slim
    steps:
    - checkout
    - restore_cache:
        keys:
        - puppet-check-ruby-<< parameters.ruby-version >>
    - run:
        name: package prereq install
        command: apt-get install cmake
    - run:
        name: bundler install
        command: bundle install --retry=3 && bundle binstubs puppet
    - run:
        name: display puppet version
        command: puppet --version
    - run:
        name: execute tests
        command: bundle exec rake unit system # default for 2.5
    - save_cache:
        paths:
        - ~/.bundle
        key: puppet-check-ruby-<< parameters.ruby-version >>

workflows:
  execute_tests:
    jobs:
    - test:
        matrix:
          parameters:
            ruby-version:
            - '2.2'
            - '2.3'
            - '2.4'
            - '2.5'
            - '2.6'
            - '2.7'
            - '3.0'
