---
name: ci

on:
  push:
    branches: [master]
    paths:
    - 'lib/**'
    - 'spec/**/*_spec.rb'
  pull_request:
    branches: [master]
    paths:
    - 'lib/**'
    - 'spec/**/*_spec.rb'

jobs:
  test:
    strategy:
      matrix:
        ruby_version:
        - '2.7'
        - '3.4'
    runs-on: ubuntu-latest
    container: ruby:${{ matrix.ruby_version }}-slim
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install some prerequisite packages
      run: apt-get update && apt-get install -y cmake pkg-config openssl
    - name: bundler install
      run: bundle install --retry=3
    - name: run tests
      run: bundle exec rake unit system
